Radio
js-tasks-ru/htmlcss-20210708_hawkridge pull request #16
Opened 2021-08-01 19:38 UTC by hawkridge

2021-08-01 19:38 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-08-01 19:41 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-08-01 19:43 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-08-01 19:46 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-08-01 20:01 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-08-01 20:24 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-08-02 14:30 UTC, GSemikozov requested changes

2021-08-02 14:30 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +    background: url(../../assets/images/radio-marker.svg) no-repeat;
чтобы не создавать отдельные иконки и чтобы браузер не выполнял дополнительный запрос, лучше кружок отрисовать через css

2021-08-03 05:55 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-08-03 05:58 UTC, hawkridge commented on 07-lection5/02-radio/radio.css
> +    background: url(../../assets/images/radio-marker.svg) no-repeat;
поправил

2021-08-03 19:44 UTC, GSemikozov approved these changes

2021-08-03 19:45 UTC, merged