feat(): add normalize, create primary, secondary and alternate buttons
js-tasks-ru/htmlcss-20210708_hawkridge pull request #3
Opened 2021-07-15 06:53 UTC by hawkridge

2021-07-15 06:54 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-07-15 13:42 UTC, GSemikozov requested changes

2021-07-15 13:42 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +button {
если "сбросы" стилей задаем не в самом классе блока, то тогда можно вынести в normalize.css (или что по итогу выбрано для общих сбросов стилей)

2021-07-15 13:42 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.btn-primary,
все модификаторы нужно поправить, правильно писать через нижнее подчеркивание - `.btn_primary`

2021-07-15 13:42 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    opacity: .5;
для всех disabled элементов рекомендуется указывать pointer-events: none чтобы пользователь не мог нажать на такой элемент или как-то взаимодействовать с ним

2021-07-15 13:42 UTC, GSemikozov commented on 03-lection1/01-button/utils.css
> +    width: 960px;
наш контейнер по дизайну 1110px)

2021-07-15 13:42 UTC, GSemikozov commented on assets/css/main.css
> +    font-size: 16px;
лучше не стоит прям всем элементам задавать один сайз - потом придется во многих элементах переопределять

2021-07-17 18:30 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-07-17 18:30 UTC, hawkridge commented on 03-lection1/01-button/button.css
> +button {
Перенесено в блок класса

2021-07-17 18:31 UTC, hawkridge commented on 03-lection1/01-button/button.css
> +.btn-primary,
done

2021-07-17 18:32 UTC, hawkridge commented on 03-lection1/01-button/button.css
> +    opacity: .5;
done. А разве браузер по дефолту не ставит pointer events none для button[disabled]? обработчики точно перестают на нем работать сами

2021-07-17 18:32 UTC, hawkridge commented on 03-lection1/01-button/utils.css
> +    width: 960px;
done

2021-07-17 18:32 UTC, hawkridge commented on assets/css/main.css
> +    font-size: 16px;
done

2021-07-17 19:09 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-18 09:41 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    opacity: .5;
hover например продолжает работать

2021-07-18 09:41 UTC, GSemikozov approved these changes

2021-07-18 09:41 UTC, merged